# Generated by Django 2.1.5 on 2021-08-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('course', models.CharField(max_length=60)),
                ('instructor', models.CharField(max_length=60)),
                ('duration', models.FloatField()),
            ],
        ),
    ]