# Generated by Django 2.1.5 on 2022-06-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('stickers', 'stickers'), ('t-shirts', 't-shirts'), ('artwork', 'artwork'), ('coloring books', 'coloring books'), ('monthly planners', 'monthly planners')], max_length=60),
        ),
    ]
